### ISSUE TITLE
Script tags not receiving integrity attributes

### ISSUE THREAD

**Issue by mwpastore** [jonathanKingston/ember-cli-sri#20] opened 2016-02-11 22:00 UTC
Hi folks. Sorry for the question-like issue report but not sure where else to ask. I'm just getting started with SRI. My link tags are receiving an integrity attribute after installing and enabling ember-cli-sri but my script tags are not. I thought maybe it was due to the paranoiaCheck but it looks like it is disabled by default the current version of broccoli-sri-hash. Any suggestions?

**Comment by jonathanKingston** [comment] 2016-02-11 22:36
Hey!

- Do you use the default settings rather than change the `SRI` settings?
- Are the paths relative?
- Do you have a base tag?
- Is this being built as production?
- Are you getting fingerprinting output on the JS ie does `filenames.js` become `filename-1d623b89683f9ce4e074de1676d12416.js`?

**Comment by mwpastore** [comment] 2016-02-11 22:42
Hi Jonathan, thank you for the quick response!

- I don't know what you mean by default settings. If I don't set `SRI.crossorigin = 'anonymous'` in ember-cli-build.js, nothing gets integrity attributes. If I set `SRI.crossorigin = 'anonymous'`, only link tags (i.e. .css files) get integrity attributes.
- I have a `fingerprint.prepend` (CloudFront), so the paths are absolute.
- Not sure what you mean by base tag?
- Yes, production.
- Yes, fingerprinting and prepending are working fine for both .css and .js files. I'm using an ember-cli-deploy pipeline. [Here](https://d1ed7tbdev34wo.cloudfront.net/manifest.txt)'s my manifest.

Thank you in advance!

**Comment by jonathanKingston** [comment] 2016-02-11 23:54
- Yeah ok, you are in need of the `crossorigin` because you are using `fingerprint.prepend` as it's a cross origin request.
- `<base />` however you are not :smile:

Very curious certainly.
The code checks a few things:
- match this script check `RegExp('<script[^>]*src=["\']([^"]*)["\'][^>]*>', 'g');` https://github.com/jonathanKingston/broccoli-sri-hash/blob/d6b2038c038640efb2e769416216dce1a93cac7a/index.js#L13
- ensures the correct settings are set(which appears you have) https://github.com/jonathanKingston/broccoli-sri-hash/blob/d6b2038c038640efb2e769416216dce1a93cac7a/index.js#L185
- checks after removing the md5 and prefix that it can find the file: https://github.com/jonathanKingston/broccoli-sri-hash/blob/d6b2038c038640efb2e769416216dce1a93cac7a/index.js#L195
- Checks the hash ember computed matches the file we found: https://github.com/jonathanKingston/broccoli-sri-hash/blob/d6b2038c038640efb2e769416216dce1a93cac7a/index.js#L205

So yeah other than those, perhaps there is a bug in how the paranoiaCheck happens but I dunno why that would happen.

Is there anything different about the location of the script files or paths on disk?

**Comment by mwpastore** [comment] 2016-02-12 00:04
Oh, right, that `<base` tag. :stuck_out_tongue: I think that gets set because of the `baseURL` setting in config/environment.js; removing it removes the `<base` tag, but causes my site to not load, so that's not good!

I don't think so. I'm using the standard index.html and asset layout without any weird customization or anything. I'm not smart enough to be doing anything fancy! The fact that it can find and correctly handle the .css files seems to confirm that, no? I'm using a fairly up-to-date ember-cli (1.13.14) and I always do an `ember init` and walk through the changes. 

I am going to work for a bit and refer back to this post to see if I can figure out which of these steps is failing. I also might try creating a clean Ember project to see if I can reproduce this issue in the simplest case. If not then I know I must have some weirdness somewhere.

**Comment by jonathanKingston** [comment] 2016-02-12 00:23
Manually editing your `node_modules/ember-cli-eslint/node_modules/broccoli-sri-hash/index.js` to have `console.logs` in at build time is a simple way to debug when the tests are failing.

Yeah I'm just happy to believe there are enough moving parts to sometimes fail these checks so happy to help debug this through, you know it could even be the regex or whatever.

Sure thank you for walking through the issue, without a simpler reproduction it's pretty difficult to help however happy to help as much as possible.

**Comment by mwpastore** [comment] 2016-02-12 00:39
Sorry for spamming this issue report. I can be found on the EmberJS Community Slack if you're rather chat.

I created a brand-spanking-new project with ember-cli 1.13.14 and installed ember-cli-sri (2.0.0). With the default settings, everything works fine, but with `SRI.crossorigin = 'anonymous'` and `fingerprint.prepend` set to an absolute URL, I observe this (repeatable) behavior:

```sh
$ rm -rf dist
$ ember build --environment production
version: 1.13.14
Built project successfully. Stored in "dist/".
$ grep integrity dist/index.html 
    <link rel="stylesheet" href="http://ember-cli-sri-troubleshoot-2.example.com/assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css" integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" crossorigin="anonymous"  >
    <link rel="stylesheet" href="http://ember-cli-sri-troubleshoot-2.example.com/assets/ember-cli-sri-troubleshoot-2-d41d8cd98f00b204e9800998ecf8427e.css" integrity="sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==" crossorigin="anonymous"  >
    <script src="http://ember-cli-sri-troubleshoot-2.example.com/assets/ember-cli-sri-troubleshoot-2-20900e6612456ee9874f8e346b1dbe88.js" integrity="sha256-tbueETztFH9+e5vRfLanFvjOMwW+vnoeQatBsUiOboE= sha512-xSZ3Ryzlqpuoo6+uB0yMj5ILUqV72ouGlY4TKq/G5M5MSdTKaJ67nibjgjLH47/sM7rgGl3p0byE/kc4vvDLsg==" crossorigin="anonymous"  ></script>
```

Wait, where'd vendor.js go?

```sh
$ grep vendor..*js dist/index.html 
    <script src="http://ember-cli-sri-troubleshoot-2.example.com/assets/vendor-c38f19f6a489002c6b2517845513e2f1.js"></script>
```

It's not clear that this is the same exact issue I'm having in my project, but clearly vendor.js should be getting tagged and is not!

**Comment by jonathanKingston** [comment] 2016-02-12 02:38
:+1: looking good, will bump the broccoli version and close this after publishing and confirmation it solves your issue with the published version.

**Comment by jonathanKingston** [comment] 2016-02-12 02:50
@mwpastore published, thanks a lot for working through this! If you could let me know if that solves your issues that would be great.
I had not actually uses the extension much since the unicode was enabled so thanks for checking that through.

**Comment by mwpastore** [comment] 2016-02-12 04:35
Short answer: Yes, it solves the problem!

Longer answer: Yes, it solves the artificially-created problem, but it only fixes one of the two .js files in my real-world project. Either broccoli-asset-rev needs a tweak as well, or I found a bug in Node. I'll let you know.

**Comment by mwpastore** [comment] 2016-02-12 06:25
Well, this has been a day. I found the problem and you're not going to like it. :sweat_smile: 

The long and the short of it is that we **cannot** use the md5sum embedded in the filename as any sort of check or control. We **must** recompute the md5sum when generating the integrity. The reason for this is quite simple, but of course it took a long walk for me to come to this conclusion. 

ember-cli generates the fingerprints of the assets _before_ ember-cli-sri generates the integrity. Obviously.  But then it goes through each asset and rewrites any links to other assets to include 1. the prepend (if present) and 2. the fingerprint. Therefore, any asset that has links to other assets will **always** fail the md5sum [comparison](https://github.com/jonathanKingston/broccoli-sri-hash/blob/v2.0.0/index.js#L205), because the file contents _change_ in-between the time it's originally fingerprinted and the time it's reanalyzed for subresource integrity.

At the risk of belaboring the point, and only because I've been working on this for about eight hours now, here's an example:

#### Stage 1:

* assets/myapp.js
    * contains a link to assets/images/background.jpg
    * has a checksum of `abcd1234`
    * renamed to assets/myapp-abcd1234.js
* assets/images/background.jpg
    * has a checksum of `1111aaaa`
    * renamed to assets/images/background-1111aaaa.jpg

#### Stage 2:

* index.html
    * contains a link to assets/myapp.js
    * link is rewritten to assets/myapp-abcd1234.js
* assets/myapp-abcd1234.js
    * contains a link to assets/images/background.jpg
    * link is rewritten to assets/images/background-1111aaaa.jpg
    * now has a checksum of `wxyz6789`

#### Stage 3:

* index.html
    * contains a link to assets/myapp-abcd1234.js
        * link is inspected for subresource integrity
        * generated checksum is `wxyz6789`
        * does not match fingerprint `abcd1234`
        * link is not modified to include integrity or other attributes

--

We could disable fingerprinting for images, which would solve this exact problem, but if there's a prepend it will fail anyway. We could re-rewrite the files to strip out the prepend and any embedded fingerprints _before_ taking the md5sum, and then compare _that_ to the fingerprint, but that seems error-prone and fraught with peril. (It looks like whatever is doing that "Stage 2" rewrite subtly modifies the file in other ways, so it might not work regardless.) 

At the end of the day, I think the simplest solution is to rip out the `md5Matches` logic and just take the md5sum of the assets as-is. At the very least, maybe we introduce a new option to enable or disable `checkFingerprint`. Whatever you decide I'm happy to start chipping away at a PR... just let me know.

Thank you!

**Comment by jonathanKingston** [comment] 2016-02-13 00:57
Sorry been a little busy, yeah the md5 checking still is needed to make sure the file has one, however it isn't required to be the same as the file really (I mean ember could solve this with a build tree but this wouldn't be a quick fix).

I can remove the check or you can?

Thank you so much for working this through!

**Comment by mwpastore** [comment] 2016-02-13 02:01
No worries! Yes, I'm happy to do the legwork. Do you think it makes sense to leave the functionality in broccoli-sri-hash, but offer a way to disable it, and perhaps disable it by default in ember-cli-sri? Or should we just rip it out altogether?

**Comment by mwpastore** [comment] 2016-02-13 08:38
Hi Jonathan, I have a PR [branch](/mwpastore/ember-cli-sri/tree/add-fingerprint-check-option) ready to go for ember-cli-sri, I just need to know the version of broccoli-sri-hash that includes my two fixes (jonathanKingston/broccoli-sri-hash#17 and jonathanKingston/broccoli-sri-hash#19) and of course any guidance or feedback from you on the implementation details. Thanks in advance for your time!

**Comment by jonathanKingston** [comment] 2016-02-14 00:57
2.1.0 should be the release it is in :D thank you for your time also!
The implementation of the broccoli changes looked great so no comments there.

In the PR you have you mention the check is there for extra security `for a little extra security` which is not the case, the check was there to prevent the incorrect files from being hashed which obviously would cause issues when it went live.

**Comment by mwpastore** [comment] 2016-02-14 01:00
You're quite welcome! I reworded that statement; I'll open up a PR here so you can take a look at it more easily.

**Closed** 2016-02-18 08:01 UTC
